name: sample
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bluerabbit/actions/bin/assign@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.TOU_KEI }}
